<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <link rel="stylesheet" href="<?php echo OPTIONS['URL'] ?>/public/css/app.css<?php echo CACHE; ?>">
    <script src="<?php echo OPTIONS['URL'] ?>/public/js/lang/<?php echo OPTIONS['SITE_LANG'] ?>.js<?php echo CACHE; ?>"></script>
    <link rel="shortcut icon" href="<?php echo OPTIONS['URL'] ?>/public/favicon.ico">
</head>
<body>
<!-- Start main wrapper -->
<div class="main-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#" id="menu-toggle"><i class="fas fa-bars"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo OPTIONS['URL'] ?>" id="menu_dashboard"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo OPTIONS['URL'] ?>/account" id="menu_account"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo OPTIONS['URL'] ?>/logout" id="menu_logout"></a>
                </li>
            </ul>
        </div>
    </nav>
