<div class="sidebar-wrapper">
    <div class="logo-box">
        <a href="<?php echo OPTIONS['URL'] ?>">
            <img src="<?php echo OPTIONS['URL'] ?>/public/images/assets/logo.png" class="logo" title="CMS">
        </a>
    </div>
    <ul class="sidebar-nav">
        <li><a href="<?php echo OPTIONS['URL'] ?>" id="sidebar_dashboard"></a></li>
        <li><a href="<?php echo OPTIONS['URL'] ?>/settings" id="sidebar_settings"></a></li>
        <li><a href="<?php echo OPTIONS['URL'] ?>/categories" id="sidebar_categories"></a></li>
        <li><a href="<?php echo OPTIONS['URL'] ?>/products" id="sidebar_products"></a></li>
        <li><a href="<?php echo OPTIONS['URL'] ?>/orders" id="sidebar_orders"></a></li>
        <li><a href="<?php echo OPTIONS['URL'] ?>/pages" id="sidebar_pages"></a></li>
    </ul>
    <div class="version">
        <span id="sidebar_version"></span> <?php echo OPTIONS['VERSION']; ?>
    </div>
</div>