<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo OPTIONS['URL'] ?>/public/css/app.css<?php echo CACHE; ?>">
    <link rel="stylesheet" href="<?php echo OPTIONS['URL'] ?>/public/css/login.css<?php echo CACHE; ?>">
    <script src="<?php echo OPTIONS['URL'] ?>/public/js/lang/<?php echo OPTIONS['SITE_LANG'] ?>.js<?php echo CACHE; ?>"></script>
    <link rel="shortcut icon" href="<?php echo OPTIONS['URL'] ?>/public/favicon.ico">
</head>
<body id="login-page">
    <div class="container">