<?php


// Get header template
include_once 'tmp/logged/header.phtml';


// Get sidebar template
include_once 'tmp/logged/sidebar.phtml';


?>
<div class="content-wrapper">
    <!-- Start alert -->
    <div id="error_box" class="hidden" role="alert">
        <span id="error_message"></span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- End alert -->
    <h1></h1>
    <div class="row">
        <div class="col-md-8">
            <form id="category_new" method="POST">
                <div class="info-box">
                    <div class="info-header" id="label_categories"></div>
                    <div class="info-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label id="label_category_name"></label>
                                    <input type="text" class="form-control" id="name" name="name" autocomplete="off" maxlength="50">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label id="label_status"></label>
                                    <select class="form-control" id="status" name="status">
                                        <option value="1" id="label_option_available"></option>
                                        <option value="0" id="label_option_draft"></option>
                                        <option value="2" id="label_option_trash"></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary update-btn" id="button_create"></button>
            </form>
        </div>
    </div>
</div>
<?php


// Get footer links template
include_once 'tmp/logged/links.phtml';


?>
<script src="<?php echo OPTIONS['URL']; ?>/public/js/components/categories.new.js<?php echo CACHE; ?>"></script>
<?php


// Get footer template
include_once 'tmp/logged/footer.phtml';


?>
