<?php


// Get header template
include_once 'tmp/logged/header.phtml';


// Get sidebar template
include_once 'tmp/logged/sidebar.phtml';


?>
<div class="content-wrapper">
    <!-- Start alert -->
    <div id="error_box" class="hidden" role="alert">
        <span id="error_message"></span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- End alert -->
    <h1></h1>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8">
            <form id="change_password" method="POST">
                <div class="info-box">
                    <div class="info-header" id="label_change_password"></div>
                    <div class="info-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label id="label_current_password"></label>
                                    <input type="password" class="form-control" id="currentPass" name="currentPass" autocomplete="off" maxlength="50">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label id="label_new_password"></label>
                                    <input type="password" class="form-control" id="newPass" name="newPass" autocomplete="off" maxlength="50">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label id="label_confirm_password"></label>
                                    <input type="password" class="form-control" id="confirmPass" name="confirmPass" autocomplete="off" maxlength="50">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary update-btn" id="button_update"></button>
            </form>
        </div>
    </div>
</div>
<?php


// Get footer links template
include_once 'tmp/logged/links.phtml';


?>
<script src="<?php echo OPTIONS['URL']; ?>/public/js/components/password.js<?php echo CACHE; ?>"></script>
<?php


// Get footer template
include_once 'tmp/logged/footer.phtml';


?>
